# Theme Github link: https://github.com/korilin/hexo-theme-particle
# Developer: korilin

# html lang
language: zh

# avatar image url
head_img: https://avatars.githubusercontent.com/u/32995274?v=4

# home page head info block
head_block_enable: true

# home page head background style.
# If you use a picture as background, you must use the css background-image attribute instead of the background attribute.
# Use image as background ==> home_background: "background-image:url('../home.jpg')"
# Use a color as background ==> home_background: "background: balck"
home_background: "background-image:url('home.jpg')"

# Particle theme icon is adopts the ant design vue icons
# Link：https://www.antdv.com/components/icon-cn/

# main menu navigation
menu:
  首页:
    icon:
      name: home
      theme: filled
    src: /
  # 分类:
  #   icon:
  #     name: book
  #     theme: filled
  #   src: /categories
  # 标签:
  #   icon:
  #     name: tags
  #     theme: filled
  #   src: /tags
  关于:
    icon:
      name: idcard
      theme: filled
    src: /about

# side info card
card:
  enable: true
  description: ['Web前端开发者', '广东广州']
  icon_links:
    github:
      icon:
        type: antd-icon
        name: github
        theme: filled
        src:
      link: https://github.com/GaryHjy
  friend_links:
    英文技术博客: https://en.korilin.com
    日语记录博客: https://jp.korilin.com

# footer info
footer:
  since: 2021
  # Customize the server domain name ICP
  ICP:
    enable: true
    url: https://beian.miit.gov.cn/
    code: 粤ICP备19097478号

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  clientID: # GitHub Application Client ID
  clientSecret: # GitHub Application Client Secret
  repo: hexo-theme-particle # The name of repository of store comments
  owner: korilin # GitHub repo owner
  admin: korilin # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: en # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.

# theme style: full / night / maiden, defalut: full
style: full
